<?php
	$TanggalCetak = date("d-m-Y H:i");

//if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//print_r($result);die();

//echo "sini";die();
//echo $title;
//echo $result[0]['TOTAL_M4'];die();
//$mpdf = new mPDF('UTF-8', 'A4');
$mpdf = new mPDF('UTF-8', Array(80,135));
$drawPerPage = 50;
$html = getStyle();
$html .= '<body><div class="body">';
$html .= getHTML($result, $title);
$html .= '</div></body>';
$mpdf->WriteHTML($html);
$mpdf->Output();

function getStyle(){
	$html = '<style type="text/css">
					body{
						font:15px Tahoma;
					}
					div.body{
						padding:-30px;
						padding-top:0px;
					}
					table{
						border-collapse:collapse;
						border-spacing:0;
						width:80%;
					}
					#footer{
						height:50px;
						line-height:50px;
						color:red;
						font-weight: bold;
						position:absolute;
						bottom:0px;
					}
				</style>';
	return $html;
	}

function getHTML($result,$title){
	global $CONF;
	$html = '
		<table width="80%" align="center" >
				<tr>
					<td style="width:20%;"></td>
					<td style="width:60%; height:20;" align="center" ></td>
					<td style="width:20%;"></td>
				</tr>	
				<tr>
					<td colspan="3" align="center"><H3>GATE PASS</H3></td>
				</tr>
				<tr>
					<td align="center" colspan="3"><H9>New Priok Container Terminal 1</H9></td>
				</tr>
				<tr>
					<td colspan="3" align="center"><h3>NPCT1</h3></td>
				</tr>
				
				<tr>
					<td colspan="3" align="center" ><img width="100" height="100" src="assets/files/qrcode/code.png"></td>
				</tr>

				<tr>
					<td align="left"><font size="2">'.substr($result[0]['NO_CONT'],0,4).'</td>
					<td align="center"><font size="2">'.$result[0]['ISO_CODE'].'</td>
					<td><font size="2"><font size="2">'.$result[0]['BRUTO'].'KG</td>
				</tr>
				<tr>
					<td><font size="2"><font size="2">'.substr($result[0]['NO_CONT'],4,7).'</td>
					<td align="center"></td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td><font size="2">FULL</td>
					<td align="center"></td>
					<td><font size="2">IMPORT</td>
				</tr>
				<tr>

					<td align="center" colspan="3"><font size="2"><H6>'.$result[0]['ANGKUTNAMA_TPS'].'</H6></td>

				</tr>
				<tr>
					<td align="center" colspan="3"><font size="2">Voyage : '.$result[0]['VOY_IN'].'/'.$result[0]['VOY_OUT'].'</td>
				</tr>
				<tr>
					<td align="center" colspan="3"><font size="2">Paid Through : '.$result[0]['WK_REQ'].'</td>
				</tr>

				<tr>
					<td></td>
					<td align="center"><H6>'.$result[0]['POD1'].'/'.$result[0]['POD2'].'</H6></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td align="center"><H6>'.$result[0]['SHIPPER'].'</H6></td>
					<td></td>
				</tr>
				<tr>
					<td align="left"><span style="font-size:9px">IMO CODE : </span></td>
					<td></td>
					<td><span style="font-size:9px">'.$result[0]['IMO'].'</span></td>
				</tr>
				<tr>
					<td align="left"><span style="font-size:9px">BC Document :</span></td>
					<td><span style="font-size:9px">'.$result[0]['NO_DOK'].'</span></font></td>
					<td></td>
				</tr>
				
				<tr>
					<td align="center" colspan="3" style="height:0">&nbsp;</td>
				</tr>
			</div>
			 <footer class="footer">
					<tr>
						<td colspan="3">
							<span style="font-size:9"><i>This document is generated by BOS - IPCTPK </i><span style="font-size:7">'.date("d-m-Y H:i").'</span></font>
						</td>
					</tr>
				</table>
			 </footer>';
	return $html;
	//}
}
