BEGIN
	DECLARE V_WK_INOUT DATETIME;
	DECLARE V_KD_ORG_SENDER INT(18);
	DECLARE V_KD_ORG_RECEIVER INT(18);
	DECLARE V_KD_ASAL_BRG VARCHAR(10);
	DECLARE V_KD_TPS VARCHAR(10);
	DECLARE V_KD_GUDANG VARCHAR(10);
	DECLARE V_KD_APRF_BC VARCHAR(20);
	DECLARE V_KD_APRF_DJP VARCHAR(20);
	DECLARE V_KD_APRF_SHL VARCHAR(20);
	DECLARE V_KD_APRF_TPS2 VARCHAR(20);
	DECLARE V_KD_SETTING INT(18);
	
	INSERT INTO t_cocostscarter_history (ID, VIN_NUMBER, NO_RANGKA, NO_MESIN, TIPE, WARNA, MERK, BRUTO, NO_SEGEL, KONDISI_SEGEL, NO_BL_AWB, TGL_BL_AWB, NO_MASTER_BL_AWB, TGL_MASTER_BL_AWB, NO_POS_BC11, KD_ORG_CONSIGNEE, KD_TIMBUN, KD_PEL_MUAT, KD_PEL_TRANSIT, KD_PEL_BONGKAR, KD_DOK_IN, NO_DOK_IN, TGL_DOK_IN, WK_IN, KD_SARANA_ANGKUT_IN, NO_POL_IN, KD_DOK_OUT, NO_DOK_OUT, TGL_DOK_OUT, WK_OUT, KD_SARANA_ANGKUT_OUT, NO_POL_OUT, KD_TPS_TUJUAN, KD_GUDANG_TUJUAN, NO_DAFTAR_PABEAN, TGL_DAFTAR_PABEAN, NO_SEGEL_BC, TGL_SEGEL_BC, NO_IJIN_TPS, TGL_IJIN_TPS, FL_TRANSFER_IN, FL_TRANSFER_OUT, WK_REKAM)
	VALUES (OLD.ID, OLD.VIN_NUMBER, OLD.NO_RANGKA, NEW.NO_MESIN, NEW.TIPE, NEW.WARNA, NEW.MERK, NEW.BRUTO, NEW.NO_SEGEL, NEW.KONDISI_SEGEL, NEW.NO_BL_AWB, NEW.TGL_BL_AWB, NEW.NO_MASTER_BL_AWB, NEW.TGL_MASTER_BL_AWB, NEW.NO_POS_BC11, NEW.KD_ORG_CONSIGNEE, NEW.KD_TIMBUN, NEW.KD_PEL_MUAT, NEW.KD_PEL_TRANSIT, NEW.KD_PEL_BONGKAR, NEW.KD_DOK_IN, NEW.NO_DOK_IN, NEW.TGL_DOK_IN, NEW.WK_IN, NEW.KD_SARANA_ANGKUT_IN, NEW.NO_POL_IN, NEW.KD_DOK_OUT, NEW.NO_DOK_OUT, NEW.TGL_DOK_OUT, NEW.WK_OUT, NEW.KD_SARANA_ANGKUT_OUT, NEW.NO_POL_OUT, NEW.KD_TPS_TUJUAN, NEW.KD_GUDANG_TUJUAN, NEW.NO_DAFTAR_PABEAN, NEW.TGL_DAFTAR_PABEAN, NEW.NO_SEGEL_BC, NEW.TGL_SEGEL_BC, NEW.NO_IJIN_TPS, NEW.TGL_IJIN_TPS, NEW.FL_TRANSFER_IN, NEW.FL_TRANSFER_OUT, NOW());
	
	SELECT A.KD_ASAL_BRG, A.KD_TPS, A.KD_GUDANG
			 INTO V_KD_ASAL_BRG, V_KD_TPS, V_KD_GUDANG
	FROM t_cocostshdr A 
	WHERE A.ID = NEW.ID
	LIMIT 0,1;
	
	SELECT DISTINCT A.KD_ORGANISASI INTO V_KD_ORG_SENDER
	FROM app_user A 
	WHERE A.KD_TPS = V_KD_TPS
			AND A.KD_GUDANG = V_KD_GUDANG
	LIMIT 0,1;
	
	IF NEW.WK_IN IS NOT NULL AND NEW.WK_OUT IS NOT NULL THEN
		IF V_KD_ASAL_BRG = '1' THEN -- BONGKARAN KAPAL
			SET V_KD_APRF_BC = 'SENTCODOUTBC';
			SET V_KD_APRF_DJP = 'SENTCODOUTDJP';
			SET V_KD_APRF_SHL = 'SENTCODOUTSHL';
			-- SET V_KD_APRF_TPS2 = 'SENTCODOUTTPS2';
			SET V_WK_INOUT = NEW.WK_OUT;
		ELSEIF V_KD_ASAL_BRG = '2' THEN -- PLP/OB IMPOR
			SET V_KD_APRF_BC = 'SENTGATEOUTIMPBC';
			SET V_KD_APRF_DJP = 'SENTGATEOUTIMPDJP';
			SET V_KD_APRF_SHL = 'SENTGATEOUTIMPSHL';
			SET V_WK_INOUT = NEW.WK_OUT;
		ELSEIF V_KD_ASAL_BRG = '3' THEN -- BARANG EKSPOR
			SET V_KD_APRF_BC = 'SENTLOADBC';
			SET V_KD_APRF_DJP = 'SENTLOADDJP';
			SET V_KD_APRF_SHL = 'SENTLOADSHL';
			SET V_WK_INOUT = NEW.WK_OUT;
		ELSEIF V_KD_ASAL_BRG = '4' THEN -- PLP/OB EKSPOR
			SET V_KD_APRF_BC = 'SENTGATEOUTEXPBC';
			SET V_KD_APRF_DJP = 'SENTGATEOUTEXPDJP';
			SET V_KD_APRF_SHL = 'SENTGATEOUTEXPSHL';
			SET V_WK_INOUT = NEW.WK_OUT;
		END IF;	
	ELSEIF NEW.WK_IN IS NOT NULL AND NEW.WK_OUT IS NULL THEN
		IF V_KD_ASAL_BRG = '1' THEN -- BONGKARAN KAPAL
			SET V_KD_APRF_BC = 'SENTDISCHBC';
			SET V_KD_APRF_DJP = 'SENTDISCHDJP';
			SET V_KD_APRF_SHL = 'SENTDISCHSHL';
			-- SET V_KD_APRF_TPS2 = 'SENTDISCHTPS2';
			SET V_WK_INOUT = NEW.WK_IN;
		ELSEIF V_KD_ASAL_BRG = '2' THEN -- PLP/OB IMPOR
			SET V_KD_APRF_BC = 'SENTGATEINIMPBC';
			SET V_KD_APRF_DJP = 'SENTGATEINIMPDJP';
			SET V_KD_APRF_SHL = 'SENTGATEINIMPSHL';
			SET V_WK_INOUT = NEW.WK_IN;
		ELSEIF V_KD_ASAL_BRG = '3' THEN -- BARANG EKSPOR
			SET V_KD_APRF_BC = 'SENTCODINBC';
			SET V_KD_APRF_DJP = 'SENTCODINDJP';
			SET V_KD_APRF_SHL = 'SENTCODINSHL';
			SET V_WK_INOUT = NEW.WK_IN;
		ELSEIF V_KD_ASAL_BRG = '4' THEN -- PLP/OB EKSPOR
			SET V_KD_APRF_BC = 'SENTGATEINEXPBC';
			SET V_KD_APRF_DJP = 'SENTGATEINEXPDJP';
			SET V_KD_APRF_SHL = 'SENTGATEINEXPSHL';
			SET V_WK_INOUT = NEW.WK_IN;
		END IF;
	END IF;
	
	-- INSERT DATA UNTUK PENGIRIMAN KE BEA CUKAI
	SET V_KD_SETTING = NULL;
	SELECT A.ID INTO V_KD_SETTING
	FROM app_setting A 
	WHERE A.KD_ORG_SENDER = V_KD_ORG_SENDER
			AND A.KD_ORG_RECEIVER = (SELECT DISTINCT ID FROM t_organisasi WHERE KD_TIPE_ORGANISASI = 'BC' LIMIT 0,1)
			AND A.KD_APRF = V_KD_APRF_BC
			AND A.KD_STATUS = 'Y';
	IF V_KD_SETTING IS NOT NULL AND V_WK_INOUT IS NOT NULL THEN
		INSERT INTO app_komunikasi (KD_SETTING, NM_TABLE, FIELD1, VALUE1, FIELD2, VALUE2, FIELD3, VALUE3, TGL_STATUS)
		VALUES (V_KD_SETTING, 't_cocostscarter', 'ID', NEW.ID, 'VIN_NUMBER', NEW.VIN_NUMBER, 'NO_RANGKA', NEW.NO_RANGKA, NOW());
	END IF;
	
	-- INSERT DATA UNTUK PENGIRIMAN KE SHIPPING LINE
	SET V_KD_SETTING = NULL;	
	SELECT A.ID INTO V_KD_SETTING
	FROM app_setting A 
	WHERE A.KD_ORG_SENDER = V_KD_ORG_SENDER
			AND A.KD_ORG_RECEIVER = (SELECT DISTINCT ID FROM t_organisasi WHERE KD_TIPE_ORGANISASI = 'SHL' LIMIT 0,1)
			AND A.KD_APRF = V_KD_APRF_SHL
			AND A.KD_STATUS = 'Y';
	IF V_KD_SETTING IS NOT NULL AND V_WK_INOUT IS NOT NULL THEN
		INSERT INTO app_komunikasi (KD_SETTING, NM_TABLE, FIELD1, VALUE1, FIELD2, VALUE2, FIELD3, VALUE3, TGL_STATUS)
		VALUES (V_KD_SETTING, 't_cocostscarter', 'ID', NEW.ID, 'VIN_NUMBER', NEW.VIN_NUMBER, 'NO_RANGKA', NEW.NO_RANGKA, NOW());
	END IF;
	
	-- INSERT DATA UNTUK PENGIRIMAN KE DJP	
	SET V_KD_SETTING = NULL;
	SELECT A.ID INTO V_KD_SETTING
	FROM app_setting A 
	WHERE A.KD_ORG_SENDER = V_KD_ORG_SENDER
			AND A.KD_ORG_RECEIVER = (SELECT DISTINCT ID FROM t_organisasi WHERE KD_TIPE_ORGANISASI = 'DJP' LIMIT 0,1)
			AND A.KD_APRF = V_KD_APRF_DJP
			AND A.KD_STATUS = 'Y';
	IF V_KD_SETTING IS NOT NULL AND V_WK_INOUT IS NOT NULL THEN
		INSERT INTO app_komunikasi (KD_SETTING, NM_TABLE, FIELD1, VALUE1, FIELD2, VALUE2, FIELD3, VALUE3, TGL_STATUS)
		VALUES (V_KD_SETTING, 't_cocostscarter', 'ID', NEW.ID, 'VIN_NUMBER', NEW.VIN_NUMBER, 'NO_RANGKA', NEW.NO_RANGKA, NOW());
	END IF;
	
	-- INSERT DATA UNTUK PENGIRIMAN KE TPS LINI 2	
	SET V_KD_SETTING = NULL;
	SELECT A.ID INTO V_KD_SETTING
	FROM app_setting A 
	WHERE A.KD_ORG_SENDER = V_KD_ORG_SENDER
			AND A.KD_ORG_RECEIVER = (SELECT DISTINCT ID FROM t_organisasi WHERE KD_TIPE_ORGANISASI = 'TPS2' LIMIT 0,1)
			AND A.KD_APRF = V_KD_APRF_TPS2
			AND A.KD_STATUS = 'Y';
	IF V_KD_SETTING IS NOT NULL AND V_WK_INOUT IS NOT NULL THEN
		INSERT INTO app_komunikasi (KD_SETTING, NM_TABLE, FIELD1, VALUE1, FIELD2, VALUE2, FIELD3, VALUE3, TGL_STATUS)
		VALUES (V_KD_SETTING, 't_cocostscarter', 'ID', NEW.ID, 'VIN_NUMBER', NEW.VIN_NUMBER, 'NO_RANGKA', NEW.NO_RANGKA, NOW());
	END IF;
END