<?php
	$TanggalCetak = date("d-m-Y H:i");
$mpdf = new mPDF('UTF-8', Array(80,135));
$drawPerPage = 50;
$html = getStyle();
$html .= '<body><div class="body">';
$html .= getHTML($result, $title);
$html .= '</div></body>';
$mpdf->WriteHTML($html);
$mpdf->Output();

function getStyle(){
	$html = '<style type="text/css">
					body{
						font:12px Tahoma;
					}
					div.body{
						padding:-30px;
						padding-top:-30px;
					}
					table{
						border-collapse:collapse;
						border-spacing:0;
						width:80%;
					}
					#footer{
						height:50px;
						line-height:50px;
						color:red;
						font-weight: bold;
						position:absolute;
						bottom:0px;
					}

				</style>';
	return $html;
}
//print_r($datafcl);die();
function getHTML($result,$title){
	//print_r($datafcl);die();
	global $CONF;

	$html = '
		<table width="100%">
				<tr>
					
					<td style="width:85%;" colspan="3"><H4>COMMON GATE IPC TPK <BR> EIR </H4></td>
					<td style="width:15%;"><img width="80" height="50" src="assets/images/ipc_logo.png"></td>
				</tr>
				<tr>
					<td ><font size="2">Time</font></td>
					<td>:</td>
					<td ><font size="2"><span style="font-size:8">'.$result['WK_GATEOUT'].'</span></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Lic Plate</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['NO_TRUCK'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Truck Company</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['TRUCK_COMPANY'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">TID Number</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['NO_TRUCK'].'</td>
					<td></td>
				</tr>
				<tr>
					<td colspan="4"><hr></td>
				</tr>
				<tr>
					<td ><font size="2">Move</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Container</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['NO_CONT'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Line</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['LINE'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">ISO</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['ISO_CODE'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">LL</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>		
				<tr>
					<td ><font size="2">HH</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">BB</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Type</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">MAT</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">REF</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Condition</font></td>
					<td>:</td>
					<td colspan="2"><font size="1">'.$result['KONDISI'].'</td>
				</tr>
				<tr>
					<td ><font size="2">IMDG</font></td>
					<td>:</td>
					<td ><font size="2"></td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Damage</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['DAMAGE'].'</td>
					<td></td>
				</tr>
				<tr>
					<td ><font size="2">Seals</font></td>
					<td>:</td>
					<td ><font size="2">'.$result['NO_SEAL'].'</td>
					<td></td>
				</tr>
		</table>	
			 <footer class="footer">
				<p>
					<font size="1"><i>This document is generated by BOS - IPC TPK </i><span style="font-size:9">'.date("d-m-Y H:i").'</span>
				</p>
			 </footer>';
	return $html;
	//}
}
