<?php 

$mpdf = new mPDF('UTF-8', Array(80,135));
$drawPerPage = 50;
$html = getStyle();
$html .= '<body><div class="body">';
$html .= getHTML($data, $title);
$html .= '</div></body>';
$mpdf->WriteHTML($html);
$mpdf->Output();

function getStyle(){
	$html = '<style type="text/css">
					body{
						font:12px Tahoma;
					}
					div.body{
						padding:-30px;
						padding-top:-30px;
					}
					table{
						border-collapse:collapse;
						border-spacing:0;
						width:80%;
					}
					#footer{
						height:50px;
						line-height:50px;
						color:red;
						font-weight: bold;
						position:absolute;
						bottom:0px;
					}

				</style>';
	return $html;
}
function getHTML($data,$title){
	global $CONF;

	$html = '
		<table width="100%">
				<tr>
					
					<td style="width:85%;" colspan="3"><H4>COMMON GATE IPC TPK <BR> CMS </H4></td>
					<td style="width:15%;"><img width="80" height="50" src="assets/images/ipc_logo.png"></td>
				</tr>
				<tr>
					<td colspan="4"><hr></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Daily Seq No</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['DAILYSECNO'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Truck-In Time</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['TGL'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Container No.</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['NO_CONT'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Operator</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['OPERATOR'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Class</td>
					<td >: </td>
					<td  align="left"><font size="2">EX BEHANDLE</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Status</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['STATUS'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Line Number</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['LINE'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Size/Type (ISOCODE)</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['ISO_CODE'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Weight</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['WEIGHT'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Yard Position</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['YARDPOST'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Truck Flat</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['NO_TRUCK'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Truck License</td>
					<td >: </td>
					<td  align="left"><font size="2">'.$data['NO_TRUCK'].'</td>
					<td></td>
				</tr>
				<tr>
					<td  align="left"><font size="2">Date / Time</td>
					<td >: </td>
					<td  align="left"><font size="2">'.date('d-m-Y H:i').'</td>
					<td></td>
				</tr>
		</table>
			 <footer class="footer">
				<p>
					<font size="1"><i>This document is generated by BOS - IPC TPK </i><span style="font-size:9">'.date("d-m-Y H:i").'</span>
				</p>
			 </footer>';
	return $html;
	//}
}
