
<?php //if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//print_r($result);die();

//echo "sini";die();
//echo $title;
//echo $result[0]['TOTAL_M4'];die();
$mpdf = new mPDF('UTF-8', Array(80,135));
$drawPerPage = 50;
$html = getStyle();
$html .= '<body><div class="body">';
$html .= getHTML($result, $title);
$html .= '</div></body>';
$mpdf->WriteHTML($html);
$mpdf->Output();

function getStyle(){
	$html = '<style type="text/css">
					body{
						font:15px Tahoma;
					}
					div.body{
						padding:-30px;
						padding-top:0px;
					}
					table{
						border-collapse:collapse;
						border-spacing:0;
						width:80%;
					}
					#footer{
						height:50px;
						line-height:50px;
						color:red;
						font-weight: bold;
						position:absolute;
						bottom:0px;
					}
				</style>';
	return $html;
}
//print_r($datafcl);die();
function getHTML($result,$title){
	//print_r($datafcl);die();
	if($result[0]['JNS_CONT'] == "F"){
		$JNS_CONT = "FULL";
	}else{
		$JNS_CONT = "EMPTY";
	}
	global $CONF;
	if ($result[0]['PLUG_END_DATE'] != '') {
		$exprir = date('d-m-Y H:i',strtotime($result[0]['PLUG_END_DATE']));
	}else{
		$exprir = date('d-m-Y',strtotime($result[0]['EXPIRED_DATE'])).' 23:59';
	}
	$html = '
		<table width="80%">
				<tr>
					<td style="width:15%;"><img width="80" height="75" src="assets/images/Logomti.png"></td>
					<td style="width:70%; height:20;" align="center" ><H2>GATE PASS</H2><br></td>
					<td style="width:15%;" rowspan="2"><img width="80" height="80" src="assets/files/qrcode/code.png"></td>
				</tr>
				<tr>
					<td></td>
					<td align="center"><H4>'.$exprir.'</H4></td>
					<td></td>
				</tr>
				<tr>
					<td align="center" colspan="3"><H9>PT. MULTI TERMINAL INDONESIA</H9></td>
				</tr>
				<tr>
					<td></td>
					<td align="center" style="height:20;"><H8> COMMON GATE</H8></td>
					<td></td>
				</tr>
				<tr>
					<td align="left">'.substr($result[0]['NO_CONT'],0,4).'</td>
					<td align="center">'.$result[0]['ISO_CODE'].'</td>
					<td align="right">'.$result[0]['BRUTO'].' KG</td>
				</tr>
				<tr>
					<td>'.substr($result[0]['NO_CONT'],4,6).'   '.substr($result[0]['NO_CONT'],10,1).'</td>
					<td align="center"><H4>DELIVERY <br>EX BEHANDLE</H4></td>
					<td></td>
				</tr>
				<tr>
					<td>'.$result[0]['TIPE'].'</td>
					<td align="center">'.$result[0]['NM_KAPAL'].'</td>
					<td></td>
				</tr>
				<tr>
					<td align="center" colspan="3">Voyage : '.$result[0]['NO_VOY'].'</td>
				</tr>
				<tr>
					<td></td>
					<td align="center">'.$result[0]['PEL_BONGKAR'].' / '.$result[0]['PEL_MUAT'].'</td>
					<td></td>
				</tr>
				<tr>
					<td align="center" colspan="3"><H9>'.$result[0]['NAMA_CUST'].'</H9></td>
				</tr>
				<tr>
					<td></td>
					<td align="center"><H6>'.$result[0]['CONSIGNEE'].'</H6></td>
					<td></td>
				</tr>
				<tr>
					<td align="left"><font size="1">IMO CODE</font></td>
					<td ></td>
					<td ></td>
				</tr>
				<tr>
					<td align="left"><font size="2">NO SPPB</font></td>
					<td ><font size="1">: '.$result[0]['NO_DOK'].'</font></td>
					<td></td>
				</tr>
				<tr>
					<td width:40px align="left"><font size="2">DATE SPPB</font></td>
					<td><font size="1">: '.$result[0]['TGL_DOK'].'</font></td>
					<td></td>
				</tr>
				<tr>
					<td width:40px align="left"><font size="2">NO SEAL</font></td>
					<td><font size="1">: '.$result[0]['NO_SEAL'].'</font></td>
					<td></td>
				</tr>
				<tr>
					<td align="center" colspan="3" style="height:15">&nbsp;</td>
				</tr>
				
			 <footer class="footer">
					<tr>
						<td colspan="3">
							<font size="1"><i>This document is generated by BOS - PT. MTI </i><span style="font-size:9">'.date("d-m-Y H:i").'</span></font>
						</td>
					</tr>
				</table>
			 </footer>';
	return $html;
	//}
}
